spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  name: new_element.history
  exchange: history.exchange
  # durable: true
  # exclusive: false
  # autoDelete: false